employee_directory/employee_directory/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employees.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employee_directory/employees/urls.py
from django.urls import path
# from employees.views import index
from .views import (
    Index,
    AllWorkersListVew,
    OneWorker,
    AllWorkersListAjaxView
)

app_name = 'employees'

urlpatterns = [
    path('', Index.as_view(), name='index'),

    path('all_workers/', AllWorkersListVew.as_view(), name='all_workers'),
    path('all_workers/ajax/', AllWorkersListAjaxView.as_view(), name='all_workers_ajax'),

    path('one_worker/id=<int:pk>/', OneWorker.as_view(), name='one_worker'),
]

employee_directory/employees/models.py
from django.db import models

# Create your models here.


class JobTitle(models.TextChoices):
    '''профессии'''
    number_5 = ('OM', 'Ordinary Worker')
    number_4 = ('DP', 'Department Head')
    number_3 = ('MN', 'Manager')
    number_2 = ('DI', 'Director')
    number_1 = ("BG", 'Big Boss')


class Employees(models.Model):
    '''таблица работника'''
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    job_title = models.CharField(
        choices=JobTitle.choices,
        max_length=2
    )
    salary = models.IntegerField()
    recruitment = models.DateField(auto_now_add=True)
    supervisor = models. ForeignKey(
        'self',
        on_delete=models.PROTECT,
        related_name='boss',
        verbose_name='Руководитель',
        blank=True,
        null=True
    )

    class Meta:
        ordering = ['id']

employee_directory/employees/forms.py
from django.forms import ModelForm
from .models import Employees
from django.forms import (
    ModelForm,
    TextInput,
    Select,
    NumberInput
)


class EmployeesForm(ModelForm):

    class Meta:
        model = Employees
        # fields = ['first_name', 'last_name', 'sur_name', 'salary', 'job_title']
        fields = '__all__'

        widgets = {
            'first_name': TextInput(attrs={
                'class': 'form-control',
                'id': 'id-first_name',
                # 'placeholder': '.'
            }),
            'last_name': TextInput(attrs={
                'class': 'form-control',
                'id': 'id-last_name',
            }),
            'salary': NumberInput(attrs={
                'class': 'form-control',
                'id': 'id-salary',
            }),
            'job_title': Select(attrs={
                'class': 'form-control',
                'id': 'id-job_title',
            }),
            'supervisor': Select(attrs={
                'class': 'form-control',
                'id': 'id-supervisor',
            })
        }

employee_directory/employees/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.http import HttpResponse
from django.template.loader import render_to_string

from django.views import View

from .models import Employees
from .forms import EmployeesForm

from django.db.models import Q


# Create your views here.

def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'


class Index(View):
    form_class = EmployeesForm
    initial = {'key': 'value'}
    template_name = 'index.html'

    def get(self, request):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect('all_workers')
        else:
            return render(request, self.template_name, {'form': form})


class AllWorkersListVew(ListView):
    '''список всех работников'''
    model = Employees
    template_name = 'all_workers.html'
    paginate_by = 500

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            object_list = Employees.objects.filter(
                Q(first_name__icontains=query) | Q(last_name__icontains=query)
            )
        else:
            sort_order = self.request.GET.get('sort', 'id')
            # object_list = Employees.objects.all()
            object_list = Employees.objects.order_by(sort_order)

        return object_list


class AllWorkersListAjaxView(AllWorkersListVew):
    template_name = 'sorted_list.html'

    def get_queryset(self):
        sort_order = self.request.GET.get('sort', '-id')
        print('-'*70)
        print(sort_order)
        return Employees.objects.order_by(sort_order)

    def render_to_response(self, context, **response_kwargs):
        if self.request.is_ajax():
            html = render_to_string(self.template_name, context)
            return HttpResponse(html)
        else:
            return super().render_to_response(context, **response_kwargs)


class OneWorker(ListView):
    '''один работник с подчиненными и руководителем'''
    model = Employees
    template_name = 'one_worker.html'
    context_object_name = 'one_worker'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['worker'] = Employees.objects.get(id=self.kwargs['pk'])
        return context

employee_directory/templates/all_workers.html
{% extends "base.html" %}

{% block tittle %}all workers{% endblock tittle %}

{% block data %}
    <div class="two-form">
        <form id="sort-form" class="dropdown">
            <select class="btn btn-secondary dropdown-toggle" name="sort" onchange="submitForm()">
                <option class="dropdown-item" value="-id">Sorted -Id</option>
                <option class="dropdown-item" value="id">Sorted Id</option>
                <option class="dropdown-item" value="first_name">Name A-Z</option>
                <option class="dropdown-item" value="-first_name">Name Z-A</option>
                <option class="dropdown-item" value="last_name">Surname A-Z</option>
                <option class="dropdown-item" value="-last_name">Surname A-Z</option>
                <option class="dropdown-item" value="salary">Salary</option>
                <option class="dropdown-item" value="-salary">-Salary</option>
                <option class="dropdown-item" value="-recruitment">Date</option>
                <option class="dropdown-item" value="-recruitment">-Date</option>
            </select>
        </form>
        <nav class="navbar bg-body-tertiary">
      <div>
        <form id="search-form" action="{% url 'employees:all_workers' %}" class="d-flex" role="search" method="get">
          {% csrf_token %}
          <input class="form-control me-2" type="text" placeholder="Write Name or Surname" aria-label="Search" name="q">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </nav>
    </div>
  {% if object_list %}
      <table class="table table-striped table-hover">
          <tr>
              <th id="" scope="col">ID</th>
              <th scope="col">Name</th>
              <th scope="col">Surname</th>
              <th scope="col">Job title</th>
              <th scope="col">Salary</th>
              <th scope="col">Employment date</th>
              <th scope="col">Supervisor</th>
          </tr>
      {% for worker in object_list %}
          <tr id="model-list" >
              <th scope="row"><a href="/" class="not-border"><div class="all-place">{{ worker.id }}</div></a></th>
              <td><a href="{% url 'employees:one_worker' pk=worker.id %}" class="not-border"><div class="all-place">{{ worker.first_name }}</div></a></td>
              <td><a href="{% url 'employees:one_worker' pk=worker.id %}" class="not-border"><div class="all-place">{{ worker.last_name }}</div></a></td>
              <td><a href="{% url 'employees:one_worker' pk=worker.id %}" class="not-border"><div class="all-place">{{ worker.job_title }}</div></a></td>
              <td><a href="{% url 'employees:one_worker' pk=worker.id %}" class="not-border"><div class="all-place">{{ worker.salary }}</div></a></td>
              <td><a href="{% url 'employees:one_worker' pk=worker.id %}" class="not-border"><div class="all-place">{{ worker.recruitment }}</div></a></td>
              <td><a href="{% url 'employees:one_worker' pk=worker.id %}" class="not-border"><div class="all-place">{{ worker.supervisor.first_name }} {{ worker.supervisor.sur_name }} {{ worker.supervisor.last_name }}</div></a></td>
          </tr>
      {% endfor %}
    </table>
        {% if is_paginated %}
            <nav class="" aria-label="Page navigation example">
              <ul class="pagination justify-content-center">
                <li class="page-item">
                    {% if page_obj.has_previous %}
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}"><<<</a>
                    {% else %}
                    <p class="page-link"><<<</p>
                    {% endif %}
                </li>
                <li class="page-item"><p class="page-link">{{ page_obj.number }}/{{ page_obj.paginator.num_pages }}</p></li>
                <li class="page-item">
                    {% if page_obj.has_next %}
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">>>></a>
                    {% else %}
                    <p class="page-link">>>></p>
                    {% endif %}
                </li>
              </ul>
            </nav>
        {% endif %}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  {% else %}
      <p>No employees found with this name!</p>
  {% endif %}

{% endblock data %}

employee_directory/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'CSS/style.css' %}">
    <title>{% block tittle %}Title{% endblock tittle %}</title>
</head>

<body>
  <div id="content" class="container d-flex flex-column justify-content-center align-items-center ">
    {% block data %}{% endblock data %}
  </div>
  <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

</html>

employee_directory/templates/index.html
{% extends "base.html" %}

{% block tittle %}main page{% endblock tittle %}

{% block data %}

  <div class="d-flex flex-column three-roads">
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
      Register a new employee!
    </button>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Registering a new employee!</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form method="POST">{% csrf_token %}
            <div class="mb-3">
              <label for="id-first_name" class="form-label">Employee name</label>
                {{ form.first_name }}
            </div>
            <div class="mb-3">
              <label for="id-last_name" class="form-label">Employee last name</label>
                {{ form.last_name }}
            </div>
            <div class="mb-3">
              <label for="id-job_title" class="form-label">Employee's position</label>
                {{ form.job_title }}
            </div>
            <div class="mb-3">
              <label class="form-label">Employee salary</label>
                {{ form.salary }}
            </div>
            <div class="mb-3">
              <label for="id-supervisor" class="form-label">Employee's immediate supervisor</label>
                {{ form.supervisor }}
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Save</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

  <a class="btn btn-primary mt-2" href="{% url 'employees:all_workers' %}">All workers</a>

{% endblock data %}

employee_directory/templates/one_worker.html
{% extends "base.html" %}

{% block tittle %}one worker{% endblock tittle %}

{% block data %}
    {% if worker.supervisor %}
        <a href="{% url 'employees:one_worker' pk=worker.supervisor.id %}"><h2>{{ worker.supervisor.first_name }} {{ worker.supervisor.last_name }}</h2></a>
        <p>↓</p>
    {% else %}
        <h2>It's main Boss!</h2>
    {% endif %}

    <h3>{{ worker.first_name }} {{ worker.last_name }}</h3>
    {% if worker.boss.all %}
            <p>↓</p>
        {% for subordinate in worker.boss.all %}
            <a href="{% url 'employees:one_worker' pk=subordinate.id %}"><h4> - {{ subordinate.first_name }} {{ subordinate.last_name }}</h4></a>

        {% endfor %}
    {% endif %}

{% endblock data %}

employee_directory/templates/sorted_list.html
<table class="table table-striped table-hover">
  <tr>
      <th id="" scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">Surname</th>
      <th scope="col">Job title</th>
      <th scope="col">Salary</th>
      <th scope="col">Employment date</th>
      <th scope="col">Supervisor</th>
  </tr>
{% for worker in object_list %}
  <tr>
      <th scope="row"><a href="/" class="not-border"><div class="all-place">{{ worker.id }}</div></a></th>
      <td><a href="{% url 'employees:one_worker' pk=worker.id %}" class="not-border"><div class="all-place">{{ worker.first_name }}</div></a></td>
      <td><a href="{% url 'employees:one_worker' pk=worker.id %}" class="not-border"><div class="all-place">{{ worker.last_name }}</div></a></td>
      <td><a href="{% url 'employees:one_worker' pk=worker.id %}" class="not-border"><div class="all-place">{{ worker.job_title }}</div></a></td>
      <td><a href="{% url 'employees:one_worker' pk=worker.id %}" class="not-border"><div class="all-place">{{ worker.salary }}</div></a></td>
      <td><a href="{% url 'employees:one_worker' pk=worker.id %}" class="not-border"><div class="all-place">{{ worker.recruitment }}</div></a></td>
      <td><a href="{% url 'employees:one_worker' pk=worker.id %}" class="not-border"><div class="all-place">{{ worker.supervisor.first_name }} {{ worker.supervisor.sur_name }} {{ worker.supervisor.last_name }}</div></a></td>
  </tr>
{% endfor %}